import Head from 'next/head'
import { FC, ReactNode } from 'react'

export type Props = {
  title?: string
  children: ReactNode
}

export const Layout: FC<Props> = (props) => (
  <>
    <Head>
      <title>Kotlin User Groups{props.title ? `: ${props.title}` : ''}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {props.children}
  </>
)
